In [3]:
from databricks import sql
import pandas as pd

In [5]:

def tabla(db,tabla):
    connection =  sql.connect(server_hostname = 'dbc-156e0dba-cc88.cloud.databricks.com',
                              http_path       = 'sql/protocolv1/o/3085278994866805/0907-021244-iq24n037',
                              access_token    = 'dapi400119482528a0aceea05ccffcedcc59')

    cursor = connection.cursor()
    cursor.execute(f"SELECT * FROM {db}.{tabla}")
    result = cursor.fetchall()
    df = pd.DataFrame(result)
    cursor.close()
    connection.close()
    return df

In [ ]:
df = tabla(silver, ny_city_data)

In [9]:
df

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,4547589,Backing Unsafely,Unspecified,2022-07-20T00:00:00.000,1:25,40.835808,"[(human_address, {""address"": """", ""city"": """", ""...",-73.89083,0,0,...,None,None,None,None,None,None,None,None,None,None
1,4548075,Unsafe Speed,Unspecified,2022-07-21T00:00:00.000,5:20,None,None,None,0,0,...,None,None,None,None,None,None,None,None,None,None
2,4407480,Following Too Closely,Unspecified,2021-04-14T00:00:00.000,5:32,None,None,None,0,0,...,None,None,None,None,None,None,None,None,None,None
3,4407147,Unspecified,None,2021-04-13T00:00:00.000,21:35,40.6835800,"[(latitude, 40.68358), (longitude, -73.97617)]",-73.9761700,0,0,...,BROOKLYN,620 ATLANTIC AVENUE,11217,None,None,None,None,None,None,None
4,4407665,Pavement Slippery,None,2021-04-15T00:00:00.000,16:15,None,None,None,0,0,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,4551470,Driver Inattention/Distraction,Failure to Yield Right-of-Way,2022-07-28T00:00:00.000,21:00,40.759895,"[(human_address, {""address"": """", ""city"": """", ""...",-73.823944,1,0,...,None,None,None,None,None,None,None,None,None,None
9996,4551539,Unspecified,None,2022-07-24T00:00:00.000,3:00,40.76244,"[(human_address, {""address"": """", ""city"": """", ""...",-73.99033,0,0,...,MANHATTAN,403 WEST 48 STREET,10036,None,None,None,None,None,None,None
9997,4551347,Driver Inattention/Distraction,Unspecified,2022-07-25T00:00:00.000,14:20,40.728947,"[(human_address, {""address"": """", ""city"": """", ""...",-73.92793,0,0,...,None,None,None,None,None,None,None,None,None,None
9998,4551018,Fell Asleep,Unspecified,2022-07-30T00:00:00.000,7:03,40.709305,"[(human_address, {""address"": """", ""city"": """", ""...",-73.907005,0,0,...,QUEENS,None,11385,BLEECKER STREET,None,None,None,None,None,None
9999,4551398,Unsafe Speed,Unspecified,2022-07-30T00:00:00.000,10:40,40.806496,"[(human_address, {""address"": """", ""city"": """", ""...",-73.94009,1,0,...,MANHATTAN,1971 MADISON AVENUE,10035,None,None,None,None,None,None,None

In [1]:
class coso():
    def __init__(self,endpoint,tabla):
        self.endpoint = endpoint
        self.table = tabla

In [3]:
coso = coso('hola','mundo')

In [4]:
coso.endpoint

'hola'